module.exports = {
  projects: [
    '<rootDir>/apps/extension',
    '<rootDir>/apps/server',
    '<rootDir>/libs/scraper',
    '<rootDir>/apps/queue',
    '<rootDir>/apps/web',
    '<rootDir>/libs/lib/shared/config',
    '<rootDir>/libs/shared/config',
    '<rootDir>/apps/scraper',
    '<rootDir>/apps/worker',
    '<rootDir>/apps/monitor',
    '<rootDir>/libs/data-access/util-prisma',
    '<rootDir>/libs/data-access/util-redis',
    '<rootDir>/libs/queue',
    '<rootDir>/apps/processor',
    '<rootDir>/libs/api-wrapper/util-slack',
    '<rootDir>/libs/api-wrapper/util-mail',
  ],
};
