version: "3"

services:
    queue:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./config/redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]

    database:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
            # - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        environment:
            POSTGRES_HOST: "${DB_HOST}"
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_PORT: "${DB_PORT}"

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWORD}"
        ports:
            - "16543:80"
        depends_on:
            - database

volumes:
    postgres: